apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: irmk69yfr-nodejs 
  janus-idp.io/tekton: irmk69yfr-nodejs
  backstage.io/kubernetes-id: irmk69yfr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: irmk69yfr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml