apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: irmk69yfr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: irmk69yfr-nodejs 
  name: irmk69yfr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: irmk69yfr-nodejs 
